---
cmd: ~/po-util.sh photon build

targets:
  Build:
    args:
      - photon
      - build
    cmd: ~/po-util.sh
    keymap: ctrl-alt-1
    name: Build
  Flash:
    args:
      - photon
      - flash
    cmd: ~/po-util.sh
    keymap: ctrl-alt-2
    name: Flash
  Clean:
    args:
      - photon
      - clean
    cmd: ~/po-util.sh
    keymap: ctrl-alt-3
    name: Clean
  DFU:
    args:
      - photon
      - dfu
    cmd: ~/po-util.sh
    keymap: ctrl-alt-4
    name: DFU
  OTA:
    args:
      - photon
      - ota
      - --multi
    cmd: ~/po-util.sh
    keymap: ctrl-alt-5
    name: DFU

